# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem 'asciidoctor-pdf'
gem 'prawn', github: 'prawnpdf/prawn'
gem 'asciidoctor-diagram'

role:
  big:
    font_size: $base_font_size_large
  small:
    font_size: $base_font_size_small
  smaller:
    font_size: $base_font_size_small * 0.8
  tiny:
    font_size: $base_font_size_small * 0.5
  red:
    font_color: #ff0000
  green:
    font_color: #00aa00
  blue:
    font_color: #0000ff
  cyan:
    font_color: #00cccc
  pink:
    font_color: #cc00cc
  brown:
    font_color: #A0522D