const actionTypes = Object.freeze({
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL : 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE : 'CHANGE_LANGUAGE',
})
export default actionTypes;