from api.views.home import *
from api.views.user import *
from api.views.lirepPdf import *
from api.views.quiz import *
from api.views.question import *
from api.views.choix import *
from api.views.questionnaire import *
from api.views.historiqueAffichage import *
from api.views.pointsUser import *